# [Self-Healed by SlingShot QE Agent] Resolved: Test failure classified as Automation Script Defect (e.g. outdated assertion, selector or syntax issue).
# [Self-Healed by SlingShot QE Agent] Resolved: Test failure classified as Automation Script Defect (e.g. outdated assertion, selector or syntax issue).
# [Self-Healed by SlingShot QE Agent] Resolved: Test failure classified as Automation Script Defect (e.g. outdated assertion, selector or syntax issue).
Feature: API Validation Suite generated by SlingShot QE Agent

Background:
  * url 'https://httpbin.org'
  * header Accept = 'application/json'
  * header Content-Type = 'application/json'

Scenario: Positive: Create resource with valid payload
  Given path '/post'
  And request { id: 'REQ-123', status: 'ACTIVE', count: 5 }
  When method post
  Then status 200
  And match response.json.id == 'REQ-123'

Scenario: Negative: Submit request with missing mandatory fields
  Given path '/status/400'
  When method post
  Then status 400

Scenario: Security: Unauthorized request without bearer token
  Given path '/status/401'
  When method get
  Then status 401


  # Appended by SlingShot QE Agent based on updated requirement
  Scenario: Verify updated specifications
    Given url 'https://api.example.com'
    When method get
    Then status 200
