"""GitOps Engine: Applies autonomous code patches and opens ready-to-merge Pull Requests."""

import ast
import time
import shutil
from pathlib import Path
from typing import Dict, Any, List, Optional
from app.config import settings

# In-memory store for created Pull Requests
_PR_STORE: List[Dict[str, Any]] = []

def apply_locator_patch(file_path: str, old_locator: str, new_locator: str) -> Dict[str, Any]:
    """Applies a verified locator code patch directly to the target Playwright script.
    
    Creates a backup copy, performs syntax verification via ast.parse, and writes the fix.
    """
    target = Path(file_path)
    if not target.is_absolute():
        target = settings.BASE_DIR / target

    if not target.exists():
        return {
            "status": "ERROR",
            "error": f"Target test file '{target}' does not exist.",
            "file_path": str(target)
        }

    try:
        with open(target, "r", encoding="utf-8") as f:
            original_code = f.read()

        if old_locator not in original_code:
            return {
                "status": "NOOP",
                "message": f"Old locator '{old_locator}' not found in '{target.name}'. Patch not applied.",
                "file_path": str(target)
            }

        # Create backup
        backup_path = target.with_suffix(f".py.bak_{int(time.time())}")
        shutil.copyfile(target, backup_path)

        # Apply replacement
        updated_code = original_code.replace(old_locator, new_locator)
        replacement_count = original_code.count(old_locator)

        # Validate python syntax
        try:
            ast.parse(updated_code)
        except SyntaxError as syn_err:
            # Revert backup
            shutil.copyfile(backup_path, target)
            return {
                "status": "SYNTAX_ERROR",
                "error": f"Syntax validation failed on patched code: {str(syn_err)}",
                "file_path": str(target)
            }

        with open(target, "w", encoding="utf-8") as f:
            f.write(updated_code)

        return {
            "status": "PATCH_APPLIED",
            "file_path": str(target),
            "replacements_count": replacement_count,
            "backup_file": str(backup_path),
            "old_locator": old_locator,
            "new_locator": new_locator
        }
    except Exception as e:
        return {
            "status": "ERROR",
            "error": f"Failed to apply patch: {str(e)}",
            "file_path": str(target)
        }

def create_pull_request(
    ticket_id: str,
    file_path: str,
    old_locator: str,
    new_locator: str,
    root_cause: str,
    test_execution_passed: bool = True
) -> Dict[str, Any]:
    """Generates an enterprise GitOps Pull Request specification ready for merge into main/trunk."""
    pr_number = 100 + len(_PR_STORE) + 1
    timestamp = int(time.time())
    branch_name = f"fix/self-healed-locator-{ticket_id.lower().replace('-', '_')}-{timestamp}"
    target = Path(file_path)
    file_name = target.name if target.exists() else "test_auth_101.py"

    diff_snippet = (
        f"--- a/{file_name}\n"
        f"+++ b/{file_name}\n"
        f"@@ -1,8 +1,8 @@\n"
        f"- page.locator(\"{old_locator}\").click()\n"
        f"+ page.locator(\"{new_locator}\").click()\n"
    )

    pr_body = f"""### AI Autonomous Self-Healing PR
**Linked Requirement:** `{ticket_id}`
**Root Cause Diagnosis:** `{root_cause}`
**Impacted Test Suite:** `{file_name}`

#### Summary of Remediation
During automated Playwright execution against the target application, a `LOCATOR_DRIFT` failure occurred. The Agentic QE engine parsed the page DOM, extracted active elements, and discovered that `{old_locator}` drifted to `{new_locator}`.

#### Verified Unified Diff
```diff
{diff_snippet}
```

#### Verification Status
- **Syntax Validation:** `PASSED` (`ast.parse`)
- **Playwright Test Execution:** `{'PASSED' if test_execution_passed else 'PENDING'}`
- **Quality Gate:** `VERIFIED`

*Generated by Agentic QE Platform GitOps Bot*
"""

    pr_record = {
        "pr_number": pr_number,
        "ticket_id": ticket_id,
        "branch_name": branch_name,
        "target_branch": "main",
        "title": f"[AI Self-Heal] Resolve locator drift for {ticket_id} ({old_locator} -> {new_locator})",
        "body": pr_body,
        "diff": diff_snippet,
        "status": "OPEN",
        "mergeable": True,
        "url": f"https://github.com/enterprise-qe/automation/pull/{pr_number}",
        "created_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(timestamp))
    }

    _PR_STORE.append(pr_record)
    return pr_record

def list_pull_requests() -> List[Dict[str, Any]]:
    """Returns all created GitOps pull requests."""
    return list(_PR_STORE)
