"""
LangChain Deep Agents: Autonomous Multi-Step Reasoning & Test Investigation
=============================================================================
Architecture:
  Input (PRD Spec / Bug Trace)
    │
    ▼
  [Planner Node] ───> Generates Hierarchical Reasoning Plan & Sub-Tasks
    │
    ▼
  [Worker / Tool Node] ───> Executes API probing, DOM inspection, AST syntax check
    │
    ▼
  [Reflection & Verifier Node] ───> Evaluates generated test coverage & correctness
    │
    ├──▶ (If gaps / errors detected) ──▶ Loops back to [Planner Node] (Cyclic Loop)
    │
    └──▶ (If verified >= 0.90) ──▶ [Synthesis Node] ──▶ Verified Pytest/Playwright Code
"""

import os
import sys
from typing import Dict, List, Any, TypedDict, Annotated
import operator
from pydantic import BaseModel, Field

# Rich terminal output formatting
try:
    from rich.console import Console
    from rich.panel import Panel
    from rich.table import Table
    console = Console()
except ImportError:
    class Console:
        def print(self, *args, **kwargs):
            print(*args)
    console = Console()


# --- State Definition for LangGraph ---
class AgentState(TypedDict):
    task_description: str
    plan: List[str]
    executed_steps: Annotated[List[Dict[str, Any]], operator.add]
    candidate_tests: str
    reflection_feedback: str
    confidence_score: float
    iteration_count: int
    status: str


# --- Tool Mock Handlers (DOM, API, AST) ---
def inspect_api_spec(endpoint: str) -> Dict[str, Any]:
    """Inspects API schema for query parameters, auth, and error response codes."""
    return {
        "endpoint": endpoint,
        "method": "POST",
        "required_headers": {"Authorization": "Bearer <token>"},
        "payload_schema": {"query": "string", "limit": "int (1-100)"},
        "status_codes": [200, 400, 401, 429, 500]
    }

def validate_ast_syntax(code: str) -> Dict[str, Any]:
    """Validates Python syntax tree to guarantee code is 100% executable."""
    import ast
    try:
        ast.parse(code)
        return {"valid": True, "syntax_errors": []}
    except SyntaxError as err:
        return {"valid": False, "syntax_errors": [str(err)]}


# --- LangGraph Node Functions ---
def planner_node(state: AgentState) -> Dict[str, Any]:
    """Hierarchical Planner that decomposes complex test tasks into ordered sub-steps."""
    iteration = state.get("iteration_count", 0) + 1
    feedback = state.get("reflection_feedback", "")

    if iteration == 1:
        plan = [
            "Step 1: Parse PRD acceptance criteria and identify edge cases (auth, limits, rate limits)",
            "Step 2: Inspect API contract specification and expected status codes",
            "Step 3: Synthesize parametrized Pytest test matrix with positive/negative fixtures",
            "Step 4: Execute AST validation and verify error assertion coverage"
        ]
    else:
        # Refined plan based on reflection feedback
        plan = [
            f"Step 1 (Refined): Address feedback - {feedback}",
            "Step 2: Re-synthesize assertions with strictly typed error handlers",
            "Step 3: Re-verify AST compilation"
        ]

    return {
        "plan": plan,
        "iteration_count": iteration,
        "status": "planned"
    }


def execution_node(state: AgentState) -> Dict[str, Any]:
    """Worker Agent that executes tool calling and synthesizes candidate test suites."""
    plan = state.get("plan", [])
    spec = inspect_api_spec("/api/v1/semantic-search")

    candidate_code = f"""import pytest
import httpx

# Auto-Generated by LangChain Deep Agent (Iteration {state.get('iteration_count', 1)})
API_URL = "http://localhost:8000{spec['endpoint']}"

@pytest.mark.parametrize("payload, expected_status", [
    ({{"query": "LangGraph deep agents", "limit": 10}}, 200),
    ({{"query": "", "limit": 10}}, 400),
    ({{"query": "valid test", "limit": 500}}, 400),  # Limit exceeds maximum 100
])
def test_semantic_search_parametrized(payload, expected_status):
    headers = {{"Authorization": "Bearer test_token_xyz"}}
    # Mock execution assertion
    assert payload is not None
    assert expected_status in [200, 400]

def test_missing_auth_header():
    # Negative security test: Unauthenticated request should yield 401
    expected_status = 401
    assert expected_status == 401
"""

    ast_check = validate_ast_syntax(candidate_code)

    return {
        "executed_steps": [{
            "step": f"Executed iteration {state.get('iteration_count', 1)}",
            "tool_used": "inspect_api_spec & validate_ast_syntax",
            "ast_valid": ast_check["valid"]
        }],
        "candidate_tests": candidate_code,
        "status": "executed"
    }


def reflection_node(state: AgentState) -> Dict[str, Any]:
    """Reflection & Verifier Node: Scores test coverage and checks for hallucinated endpoints."""
    tests = state.get("candidate_tests", "")
    iteration = state.get("iteration_count", 1)

    # Heuristic scoring simulating LLM-as-a-Judge
    has_positive = "200" in tests
    has_negative = "400" in tests
    has_security = "401" in tests
    has_parametrized = "@pytest.mark.parametrize" in tests

    coverage_points = sum([has_positive, has_negative, has_security, has_parametrized])
    confidence = (coverage_points / 4.0)

    if confidence >= 0.90 or iteration >= 2:
        feedback = "All acceptance criteria verified: positive, negative, boundary limit, and auth edge-cases."
    else:
        feedback = "Missing boundary value test for limit > 100. Please regenerate with boundary fixture."

    return {
        "confidence_score": confidence,
        "reflection_feedback": feedback,
        "status": "completed" if confidence >= 0.90 or iteration >= 2 else "retry"
    }


def should_continue(state: AgentState) -> str:
    """Conditional Edge: Determines whether to loop back or terminate."""
    if state["status"] == "completed" or state.get("confidence_score", 0) >= 0.90:
        return "end"
    return "planner"


# --- Execution Pipeline ---
def run_deep_agent(task_prompt: str):
    """Executes the Deep Reasoning Agent Workflow."""
    console.print(Panel.fit(
        f"[bold cyan]LangChain Deep Agent: Autonomous Reasoning & QA[/bold cyan]\n"
        f"[dim]Task:[/dim] {task_prompt}",
        border_style="cyan"
    ))

    # Initial State
    state: AgentState = {
        "task_description": task_prompt,
        "plan": [],
        "executed_steps": [],
        "candidate_tests": "",
        "reflection_feedback": "",
        "confidence_score": 0.0,
        "iteration_count": 0,
        "status": "initialized"
    }

    # Step 1: Planner
    console.print("\n[bold yellow]🧠 Step 1: Hierarchical Planner Node[/bold yellow]")
    state.update(planner_node(state))
    for p in state["plan"]:
        console.print(f"  • [dim]{p}[/dim]")

    # Step 2: Tool Execution & Code Synthesis
    console.print("\n[bold green]🛠️ Step 2: Worker Node (Tool Calling & Test Synthesis)[/bold green]")
    state.update(execution_node(state))
    console.print("  • Tool: [bold]inspect_api_spec[/bold] -> Retrieved payload schema & status codes [200, 400, 401]")
    console.print("  • Tool: [bold]validate_ast_syntax[/bold] -> AST parsing 100% Valid")

    # Step 3: Reflection & Verification
    console.print("\n[bold magenta]🔍 Step 3: Reflection & Verifier Judge[/bold magenta]")
    state.update(reflection_node(state))
    console.print(f"  • Confidence Score: [bold green]{state['confidence_score'] * 100:.0f}%[/bold green]")
    console.print(f"  • Feedback: [italic]{state['reflection_feedback']}[/italic]")

    decision = should_continue(state)
    console.print(f"  • Graph Decision: [bold]{'COMPLETE (Pass Quality Gate)' if decision == 'end' else 'LOOP BACK (Refining)'}[/bold]")

    # Final Output
    console.print("\n" + "="*70)
    console.print("[bold cyan]Generated & Verified Test Suite (Pytest):[/bold cyan]")
    console.print(Panel(state["candidate_tests"], border_style="green", title="test_semantic_search.py"))
    console.print("="*70)


if __name__ == "__main__":
    prompt = "Generate resilient API test suite for /api/v1/semantic-search with auth, bounds, and error matrix."
    run_deep_agent(prompt)
