import type { InterviewQuestionItem } from './types';

export interface SkillMapping {
  traditionalQe: string;
  aiEngineeringEquivalent: string;
  whyItMatters: string;
  recommendedProject: string;
}

export const skillMappings: SkillMapping[] = [
  {
    traditionalQe: "Writing Automated Test Suites (Selenium / Playwright / Cypress)",
    aiEngineeringEquivalent: "Building Automated Evaluation Pipelines (DeepEval / Ragas / G-Eval)",
    whyItMatters: "Probabilistic AI applications cannot be tested with rigid assertions; they require continuous automated evaluation suites with statistical scoring.",
    recommendedProject: "AI Quality Engineering Platform"
  },
  {
    traditionalQe: "API Contract & Schema Testing (Postman / RestAssured / Pytest)",
    aiEngineeringEquivalent: "Structured Outputs & Function Calling (Pydantic / Instructor / JSON Schema)",
    whyItMatters: "Ensuring LLM API responses reliably conform to strict typed structures without breaking microservice contracts.",
    recommendedProject: "Structured Jira Ticket Extractor"
  },
  {
    traditionalQe: "Test Data Generation & Mocking (Faker / WireMock)",
    aiEngineeringEquivalent: "Synthetic Dataset Generation & Hard-Negative Mining",
    whyItMatters: "Benchmarking RAG and agents requires large golden datasets of synthetic user queries and edge cases generated by LLMs.",
    recommendedProject: "Synthetic RAG Evaluation Suite"
  },
  {
    traditionalQe: "CI/CD Quality Gates & Release Sign-offs (GitHub Actions / Jenkins)",
    aiEngineeringEquivalent: "AI Regression Benchmarks & Model Evaluation Gates",
    whyItMatters: "Preventing silent regressions, hallucination spikes, and context degradation during prompt or model version upgrades.",
    recommendedProject: "CI/CD Automated AI Gatekeeper"
  },
  {
    traditionalQe: "Bug Triage, Root Cause Analysis & Flakiness Isolation",
    aiEngineeringEquivalent: "Hallucination Detection, RAG Triad Debugging & Tracing (LangSmith / Langfuse)",
    whyItMatters: "Pinpointing whether a failure was caused by bad retrieval chunking, poor embedding similarity, prompt ambiguity, or model drift.",
    recommendedProject: "LangSmith Tracing Inspector"
  },
  {
    traditionalQe: "Security & Penetration Testing (OWASP ZAP)",
    aiEngineeringEquivalent: "Red Teaming, Prompt Injection & Jailbreak Defense Testing",
    whyItMatters: "Protecting GenAI systems against direct prompt injections, indirect jailbreaks, and sensitive data exfiltration.",
    recommendedProject: "Adversarial Prompt Red-Team Suite"
  }
];

export const interviewQuestions: InterviewQuestionItem[] = [
  {
    id: "eval-1",
    category: "AI Quality & Evaluation",
    difficulty: "Intermediate",
    question: "How do you build an automated CI/CD Quality Gate for a Generative AI application when outputs are probabilistic?",
    qeContext: "Demonstrates your ability to bridge QA automation disciplines into production AI systems.",
    answerExplanation: "Instead of binary Boolean assertions, an AI Quality Gate uses standardized scoring metrics (e.g. DeepEval G-Eval or Ragas Faithfulness) evaluated over a fixed golden benchmark dataset of 100+ versioned test cases. The CI gate calculates statistical metrics (e.g. 95th percentile faithfulness >= 0.88, hallucination rate < 3%) and compares the score distribution against the production baseline with statistical significance tests (p-value < 0.05). If degradation exceeds the defined tolerance threshold, the PR is automatically blocked.",
    keyPoints: [
      "Use version-controlled golden datasets rather than single ad-hoc prompts.",
      "Employ calibrated LLM-as-a-Judge with temperature=0 and fixed scoring rubrics.",
      "Evaluate Faithfulness, Answer Relevance, and Context Precision.",
      "Set percentile-based thresholds (p95) and regression delta limits."
    ],
    sampleFollowUp: "How do you prevent the AI Judge from having bias towards longer responses?"
  },
  {
    id: "rag-1",
    category: "RAG & Vector",
    difficulty: "Intermediate",
    question: "What is the 'RAG Triad' and how do you systematically diagnose which component caused a hallucination?",
    qeContext: "Essential for root-cause analysis in retrieval-augmented systems.",
    answerExplanation: "The RAG Triad defines the 3 fundamental quality dimensions: 1) Context Relevance (did retriever find relevant info?), 2) Groundedness/Faithfulness (did generator only use retrieved facts?), and 3) Answer Relevance (did generator answer the user's actual question?). To diagnose a hallucination: First check retrieved chunks. If the ground-truth fact is missing from the retrieved context, it is a Retrieval Failure (fix chunking, embeddings, or re-ranking). If the fact is present in the context but the LLM still made up false details, it is a Generator/Prompt Failure (adjust temperature, system prompt constraints, or model choice).",
    keyPoints: [
      "Decompose evaluation into Retrieval phase vs Generation phase.",
      "Context Precision & Context Recall measure the Retrieval phase.",
      "Faithfulness and Groundedness measure the Generation phase.",
      "Answer Relevancy measures alignment with the user's intent."
    ],
    sampleFollowUp: "What is the difference between Context Precision and Context Recall?"
  },
  {
    id: "agent-1",
    category: "Agents & MCP",
    difficulty: "Advanced",
    question: "Why are cyclic state machines (like LangGraph) preferred over linear chains for autonomous agent development?",
    qeContext: "Shows architectural maturity when building real-world AI systems.",
    answerExplanation: "Linear chains execute step A -> step B -> step C and fail if any intermediate step throws an error or requires adjustment. Real-world tasks (e.g. self-healing test execution, multi-tool querying) require reflection, retries, conditional branching, and looping until a success condition is met. LangGraph models workflows as state graphs where nodes transform state and conditional edges route execution dynamically. Furthermore, LangGraph provides state persistence and checkpointing, allowing Human-in-the-Loop approval before destructive actions.",
    keyPoints: [
      "Cyclic execution loops enable self-correction and iterative refinement.",
      "Explicit State Schemas ensure type safety across all graph nodes.",
      "Checkpointers allow pause, inspection, time-travel debugging, and resumption.",
      "Human-in-the-Loop (HITL) support for critical policy decisions."
    ],
    sampleFollowUp: "How do you prevent an agent from getting trapped in an infinite execution loop?"
  },
  {
    id: "llm-1",
    category: "LLM & Prompt",
    difficulty: "Beginner",
    question: "Why does temperature=0 not guarantee 100% deterministic reproducibility on modern GPU clusters?",
    qeContext: "Tests foundational understanding of LLM serving infrastructure.",
    answerExplanation: "While temperature=0 directs the sampling algorithm to always choose the token with the highest logit (greedy decoding), non-determinism can still occur at the hardware level. In modern GPU clusters (e.g. vLLM, TensorRT-LLM), floating-point matrix multiplications (FP16/BF16) and parallel reduction operations are executed non-associatively across concurrent CUDA threads. The slight variation in summation order introduces tiny floating-point rounding differences, which can occasionally flip the top token when two candidates have nearly identical logits.",
    keyPoints: [
      "Greedy decoding selects the argmax logit token.",
      "Floating-point operations on GPUs are non-associative due to concurrent thread execution order.",
      "Batching optimizations (dynamic batching, speculative decoding) introduce variance.",
      "Quality evaluation must account for small statistical variance."
    ],
    sampleFollowUp: "How does Top-p (nucleus) sampling differ from Top-k sampling?"
  },
  {
    id: "sys-1",
    category: "System Design & Career",
    difficulty: "Advanced",
    question: "How would you design a high-throughput, cost-optimized AI Test Generation Gateway for a 500-engineer organization?",
    qeContext: "Full-scale AI System Design interview scenario.",
    answerExplanation: "The architecture consists of: 1) Ingestion Layer: FastAPI endpoints receiving Jira webhooks and OpenAPI specs. 2) Semantic Cache: Redis vector cache with 0.92 cosine threshold to return cached test suites for identical endpoints instantly, slashing API costs. 3) Semantic Model Router: Routes simple unit tests to lightweight models (Gemini Flash) and complex end-to-end POM generation to frontier models (GPT-4o). 4) Asynchronous Worker Queue: Celery/Redis queue for batch generation with token-bucket rate limiters. 5) Sandboxed Code Evaluator: Containerized Playwright execution environment to validate TypeScript compilation before saving. 6) Observability: LangSmith + OpenTelemetry tracing latency, token spend, and DeepEval faithfulness scores.",
    keyPoints: [
      "Semantic caching slashes API expenses by 40-60%.",
      "Semantic model routing optimizes cost vs capability tradeoffs.",
      "Asynchronous message queues prevent API gateway timeouts.",
      "Sandboxed AST execution eliminates syntax errors before git commit."
    ],
    sampleFollowUp: "How do you invalidate entries in a semantic vector cache when an API schema changes?"
  }
];
