"""
Automated Playwright Test Suite for AUTH-101
Generated by Agentic QE Platform with LangGraph & Confluence RAG
Traceability: Jira AUTH-101
"""

import pytest
import time
from playwright.sync_api import Page, expect

TARGET_URL = "http://localhost:8080/login"

@pytest.fixture(autouse=True)
def setup_and_teardown(page: Page):
    """Fixture to ensure clean state before each test execution."""
    page.goto(TARGET_URL)
    # Reset any lockout state on the demo server before each run
    try:
        page.evaluate("() => fetch('/api/auth/reset', {method: 'POST'})")
    except Exception:
        pass
    yield page


def test_tc001_login_valid_credentials(page: Page):
    """TC001: Login with valid credentials and verify dashboard redirect."""
    page.goto(TARGET_URL)
    page.locator("[data-testid='input-email']").fill("customer@enterprise.io")
    page.locator("[data-testid='input-password']").fill("SecurePass123!")
    page.locator("[data-testid='button-login']").click()

    # Verify redirection and greeting
    expect(page).to_have_url(f"http://localhost:8080/dashboard", timeout=5000)
    expect(page.locator("[data-testid='user-greeting']")).to_contain_text("Welcome, Customer!")


def test_tc002_login_invalid_password(page: Page):
    """TC002: Login with invalid password and verify generic security error message."""
    page.goto(TARGET_URL)
    page.locator("[data-testid='input-email']").fill("customer@enterprise.io")
    page.locator("[data-testid='input-password']").fill("WrongPassword999!")
    page.locator("[data-testid='button-login']").click()

    error_banner = page.locator("[data-testid='alert-error']")
    expect(error_banner).to_be_visible(timeout=3000)
    expect(error_banner).to_contain_text("Invalid email or password")


def test_tc003_empty_email_validation(page: Page):
    """TC003: Validation when email field is submitted blank."""
    page.goto(TARGET_URL)
    page.locator("[data-testid='input-email']").fill("")
    page.locator("[data-testid='input-password']").fill("SecurePass123!")
    page.locator("[data-testid='button-login']").click()

    err = page.locator("[data-testid='error-email-validation']")
    expect(err).to_be_visible(timeout=3000)
    expect(err).to_contain_text("Email is required")


def test_tc004_empty_password_validation(page: Page):
    """TC004: Validation when password field is submitted blank."""
    page.goto(TARGET_URL)
    page.locator("[data-testid='input-email']").fill("customer@enterprise.io")
    page.locator("[data-testid='input-password']").fill("")
    page.locator("[data-testid='button-login']").click()

    err = page.locator("[data-testid='error-password-validation']")
    expect(err).to_be_visible(timeout=3000)
    expect(err).to_contain_text("Password is required")


def test_tc005_invalid_email_format(page: Page):
    """TC005: Validation for malformed email syntax."""
    page.goto(TARGET_URL)
    page.locator("[data-testid='input-email']").fill("customer_at_invalid")
    page.locator("[data-testid='input-password']").fill("SecurePass123!")
    page.locator("[data-testid='button-login']").click()

    err = page.locator("[data-testid='error-email-validation']")
    expect(err).to_be_visible(timeout=3000)
    expect(err).to_contain_text("Please enter a valid email address")


def test_tc006_account_lockout_after_five_failed_attempts(page: Page):
    """TC006: Verify account locks after exactly 5 consecutive failed attempts."""
    page.goto(TARGET_URL)

    # 4 consecutive invalid attempts
    for attempt in range(1, 5):
        page.locator("[data-testid='input-email']").fill("customer@enterprise.io")
        page.locator("[data-testid='input-password']").fill(f"WrongPass_{attempt}")
        page.locator("[data-testid='button-login']").click()
        expect(page.locator("[data-testid='alert-error']")).to_be_visible(timeout=3000)
        time.sleep(0.1)

    # 5th failed attempt triggers lockout
    page.locator("[data-testid='input-email']").fill("customer@enterprise.io")
    page.locator("[data-testid='input-password']").fill("WrongPass_5")
    page.locator("[data-testid='button-login']").click()

    lockout_banner = page.locator("[data-testid='alert-lockout']")
    expect(lockout_banner).to_be_visible(timeout=5000)
    expect(lockout_banner).to_contain_text("Account locked due to 5 failed attempts")
    expect(page.locator("[data-testid='button-login']")).to_be_disabled()
