"""Test Automation Code Generation Agent for SlingShot QE Agent."""

import json
from typing import Any, Dict
from langchain_core.messages import SystemMessage, HumanMessage

from slingshot_qe_agents.agents.llm_factory import get_chat_model
from slingshot_qe_agents.graph.state import QEAgentState
from slingshot_qe_agents.tools.workspace_tools import WorkspaceContextTool


class CodeGenAgent:
    """Agent that synthesizes executable test scripts (Karate DSL for API, Playwright for UI)."""

    def __init__(self, workspace_tool: WorkspaceContextTool):
        self.workspace_tool = workspace_tool
        self.llm = get_chat_model()

    def generate_new_code(self, state: QEAgentState) -> Dict[str, Any]:
        """Generate new test files from approved scenarios and save to workspace."""
        task_type = state.get("task_type", "api")
        scenarios = state.get("manual_scenarios", [])
        parsed_spec = state.get("parsed_spec", {})

        generated_files: Dict[str, str] = {}

        if task_type == "api":
            filename = "api_orders_test.feature"
            code_content = self._synthesize_karate_feature(scenarios, parsed_spec)
            generated_files[filename] = code_content
            self.workspace_tool.write_file(filename, code_content)
        else:  # ui
            filename = "test_ui_workflow.py"
            code_content = self._synthesize_playwright_test(scenarios, parsed_spec)
            generated_files[filename] = code_content
            self.workspace_tool.write_file(filename, code_content)

        return {
            "generated_code_files": generated_files,
            "hitl_checkpoint": "code_approval",
            "approval_status": "pending",
            "messages": [HumanMessage(content=f"Generated {len(generated_files)} test files in workspace: {list(generated_files.keys())}")]
        }

    def modify_existing_code(self, state: QEAgentState) -> Dict[str, Any]:
        """Suggest and apply changes to an existing test file in workspace."""
        task_type = state.get("task_type", "api")
        ws_context = state.get("workspace_context", {})
        existing_files = ws_context.get("test_files", [])
        target_file = existing_files[0] if existing_files else ("existing_api_test.feature" if task_type == "api" else "test_existing_ui.py")

        current_content = self.workspace_tool.read_file(target_file) or ""
        updated_content = current_content + f"\n\n  # Appended by SlingShot QE Agent based on updated requirement\n  Scenario: Verify updated specifications\n    Given url 'https://api.example.com'\n    When method get\n    Then status 200\n"

        self.workspace_tool.write_file(target_file, updated_content)

        return {
            "generated_code_files": {target_file: updated_content},
            "hitl_checkpoint": "code_approval",
            "approval_status": "pending",
            "messages": [HumanMessage(content=f"Modified existing test file: {target_file}")]
        }

    def _synthesize_karate_feature(self, scenarios: list, spec: dict) -> str:
        """Create Karate DSL feature file content."""
        if self.llm:
            prompt = (
                f"Generate a clean, idiomatic Karate DSL feature file (.feature) based on these scenarios:\n"
                f"{json.dumps(scenarios, indent=2)}\n\n"
                f"Spec context: {json.dumps(spec, indent=2)}\n"
                f"Output ONLY the Karate feature content without markdown code blocks."
            )
            try:
                resp = self.llm.invoke([
                    SystemMessage(content="You are an expert Karate API Test Automation Engineer."),
                    HumanMessage(content=prompt)
                ])
                content = resp.content.strip()
                if content.startswith("```"):
                    content = "\n".join(content.splitlines()[1:-1])
                return content
            except Exception:
                pass

        # Deterministic template
        feature_lines = [
            "Feature: API Validation Suite generated by SlingShot QE Agent",
            "",
            "Background:",
            "  * url 'https://httpbin.org'",
            "  * header Accept = 'application/json'",
            "  * header Content-Type = 'application/json'",
            ""
        ]

        for sc in scenarios:
            title = sc.get("title", "Scenario")
            desc = sc.get("description", "")
            feature_lines.append(f"Scenario: {title}")

            if "SIMULATE_FAIL" in title or "SIMULATE_FAIL" in desc:
                feature_lines.append("  Given path '/broken'")
                feature_lines.append("  Then SIMULATE_FAIL")
                feature_lines.append("")
                continue

            sc_type = sc.get("type", "positive")
            if sc_type == "positive":
                feature_lines.append("  Given path '/post'")
                feature_lines.append("  And request { id: 'REQ-123', status: 'ACTIVE', count: 5 }")
                feature_lines.append("  When method post")
                feature_lines.append("  Then status 200")
                feature_lines.append("  And match response.json.id == 'REQ-123'")
            elif sc_type == "negative":
                feature_lines.append("  Given path '/status/400'")
                feature_lines.append("  When method post")
                feature_lines.append("  Then status 400")
            elif sc_type == "security":
                feature_lines.append("  Given path '/status/401'")
                feature_lines.append("  When method get")
                feature_lines.append("  Then status 401")
            else:
                feature_lines.append("  Given path '/get'")
                feature_lines.append("  When method get")
                feature_lines.append("  Then status 200")
            feature_lines.append("")

        return "\n".join(feature_lines)

    def _synthesize_playwright_test(self, scenarios: list, spec: dict) -> str:
        """Create Playwright Python test file content."""
        if self.llm:
            prompt = (
                f"Generate a robust Python Playwright test file (using pytest & playwright) for:\n"
                f"{json.dumps(scenarios, indent=2)}\n"
                f"Output ONLY executable python code without markdown ticks."
            )
            try:
                resp = self.llm.invoke([
                    SystemMessage(content="You are an expert Playwright UI Automation Engineer."),
                    HumanMessage(content=prompt)
                ])
                content = resp.content.strip()
                if content.startswith("```"):
                    content = "\n".join(content.splitlines()[1:-1])
                return content
            except Exception:
                pass

        # Robust Playwright template
        return (
            'import pytest\n'
            'from playwright.sync_api import Page, expect\n\n'
            'def test_ui_navigation_and_validation(page: Page):\n'
            '    """Positive: User opens landing page and verifies elements."""\n'
            '    page.goto("https://example.com")\n'
            '    expect(page).to_have_title("Example Domain")\n'
            '    heading = page.locator("h1")\n'
            '    expect(heading).to_be_visible()\n'
            '    expect(heading).to_contain_text("Example Domain")\n\n'
            'def test_ui_negative_empty_search(page: Page):\n'
            '    """Negative: Validation checks on missing form inputs."""\n'
            '    page.goto("https://example.com")\n'
            '    # Verify links are active\n'
            '    link = page.locator("a")\n'
            '    expect(link).to_be_visible()\n'
        )
