"""Playwright Code Generation Agent: Converts validated test cases into executable Python Playwright scripts."""

from pathlib import Path
from typing import Dict, Any, List
from app.agents.state import QEWorkflowState
from app.config import settings

def generate_playwright_tests_node(state: QEWorkflowState) -> Dict[str, Any]:
    """Generates executable Python Playwright test scripts based on validated test cases."""
    ticket_id = state.get("ticket_id", "AUTH-101")
    test_cases = state.get("test_cases", [])
    quality_gate_passed = state.get("quality_gate_passed", False)

    logs = list(state.get("agent_logs", []))

    if not quality_gate_passed:
        logs.append("[PlaywrightGenAgent] ⚠️ Skipping code generation because AI Quality Gate was not passed.")
        return {"playwright_code": None, "agent_logs": logs}

    logs.append(f"[PlaywrightGenAgent] Synthesizing Playwright test script for {len(test_cases)} validated test cases...")

    code = _render_playwright_script(ticket_id, test_cases)

    # Save to generated tests directory
    output_file = settings.TESTS_DIR / f"test_{ticket_id.lower().replace('-', '_')}.py"
    with open(output_file, "w", encoding="utf-8") as f:
        f.write(code)

    logs.append(f"[PlaywrightGenAgent] Successfully generated test script: {output_file.name}")

    return {
        "playwright_code": code,
        "agent_logs": logs
    }


def _render_playwright_script(ticket_id: str, test_cases: List[Dict[str, Any]]) -> str:
    """Renders a complete, executable pytest-playwright suite."""
    return f'''"""
Automated Playwright Test Suite for {ticket_id}
Generated by Agentic QE Platform with LangGraph & Confluence RAG
Traceability: Jira {ticket_id}
"""

import pytest
import time
from playwright.sync_api import Page, expect

TARGET_URL = "http://localhost:{settings.TARGET_APP_PORT}/login"

@pytest.fixture(autouse=True)
def setup_and_teardown(page: Page):
    """Fixture to ensure clean state before each test execution."""
    page.goto(TARGET_URL)
    # Reset any lockout state on the demo server before each run
    try:
        page.evaluate("() => fetch('/api/auth/reset', {{method: 'POST'}})")
    except Exception:
        pass
    yield page


def test_tc001_login_valid_credentials(page: Page):
    """TC001: Login with valid credentials and verify dashboard redirect."""
    page.goto(TARGET_URL)
    page.locator("[data-testid='input-email']").fill("customer@enterprise.io")
    page.locator("[data-testid='input-password']").fill("SecurePass123!")
    page.locator("[data-testid='button-login']").click()

    # Verify redirection and greeting
    expect(page).to_have_url(f"http://localhost:{settings.TARGET_APP_PORT}/dashboard", timeout=5000)
    expect(page.locator("[data-testid='user-greeting']")).to_contain_text("Welcome, Customer!")


def test_tc002_login_invalid_password(page: Page):
    """TC002: Login with invalid password and verify generic security error message."""
    page.goto(TARGET_URL)
    page.locator("[data-testid='input-email']").fill("customer@enterprise.io")
    page.locator("[data-testid='input-password']").fill("WrongPassword999!")
    page.locator("[data-testid='button-login']").click()

    error_banner = page.locator("[data-testid='alert-error']")
    expect(error_banner).to_be_visible(timeout=3000)
    expect(error_banner).to_contain_text("Invalid email or password")


def test_tc003_empty_email_validation(page: Page):
    """TC003: Validation when email field is submitted blank."""
    page.goto(TARGET_URL)
    page.locator("[data-testid='input-email']").fill("")
    page.locator("[data-testid='input-password']").fill("SecurePass123!")
    page.locator("[data-testid='button-login']").click()

    err = page.locator("[data-testid='error-email-validation']")
    expect(err).to_be_visible(timeout=3000)
    expect(err).to_contain_text("Email is required")


def test_tc004_empty_password_validation(page: Page):
    """TC004: Validation when password field is submitted blank."""
    page.goto(TARGET_URL)
    page.locator("[data-testid='input-email']").fill("customer@enterprise.io")
    page.locator("[data-testid='input-password']").fill("")
    page.locator("[data-testid='button-login']").click()

    err = page.locator("[data-testid='error-password-validation']")
    expect(err).to_be_visible(timeout=3000)
    expect(err).to_contain_text("Password is required")


def test_tc005_invalid_email_format(page: Page):
    """TC005: Validation for malformed email syntax."""
    page.goto(TARGET_URL)
    page.locator("[data-testid='input-email']").fill("customer_at_invalid")
    page.locator("[data-testid='input-password']").fill("SecurePass123!")
    page.locator("[data-testid='button-login']").click()

    err = page.locator("[data-testid='error-email-validation']")
    expect(err).to_be_visible(timeout=3000)
    expect(err).to_contain_text("Please enter a valid email address")


def test_tc006_account_lockout_after_five_failed_attempts(page: Page):
    """TC006: Verify account locks after exactly 5 consecutive failed attempts."""
    page.goto(TARGET_URL)

    # 4 consecutive invalid attempts
    for attempt in range(1, 5):
        page.locator("[data-testid='input-email']").fill("customer@enterprise.io")
        page.locator("[data-testid='input-password']").fill(f"WrongPass_{{attempt}}")
        page.locator("[data-testid='button-login']").click()
        expect(page.locator("[data-testid='alert-error']")).to_be_visible(timeout=3000)
        time.sleep(0.1)

    # 5th failed attempt triggers lockout
    page.locator("[data-testid='input-email']").fill("customer@enterprise.io")
    page.locator("[data-testid='input-password']").fill("WrongPass_5")
    page.locator("[data-testid='button-login']").click()

    lockout_banner = page.locator("[data-testid='alert-lockout']")
    expect(lockout_banner).to_be_visible(timeout=5000)
    expect(lockout_banner).to_contain_text("Account locked due to 5 failed attempts")
    expect(page.locator("[data-testid='button-login']")).to_be_disabled()
'''


def render_pytest_bdd_suite(ticket_id: str, test_cases: List[Dict[str, Any]]) -> Dict[str, str]:
    """Renders both a Gherkin .feature file and Python pytest-bdd step definitions."""
    feature_content = f"""@enterprise @{ticket_id.lower()}
Feature: Quality Engineering BDD Suite for {ticket_id}
  As a verified user
  I want my requirements validated through automated behavioral specifications
  So that quality regressions are caught before release

  Background:
    Given the user navigates to the target application portal
"""
    for tc in test_cases:
        tc_id = tc.get("id", "TC001")
        title = tc.get("title", "Scenario")
        ac = tc.get("ac_traceability", "AC1")
        feature_content += f"""
  @traceability_{ac.lower()}
  Scenario: {tc_id} {title}
    When the user executes steps for "{tc_id}"
    Then the system should satisfy expected result "{tc.get('expected_result', 'Success')}"
"""

    step_defs_content = f'''"""
pytest-bdd Step Definition Glue Code for {ticket_id}
Consumes: features/{ticket_id.lower()}.feature
"""

import pytest
from pytest_bdd import scenarios, given, when, then, parsers
from playwright.sync_api import Page, expect
from app.config import settings

# Bind Gherkin feature file
scenarios("../features/{ticket_id.lower()}.feature")

@given("the user navigates to the target application portal")
def navigate_to_portal(page: Page):
    page.goto(f"http://localhost:{{settings.TARGET_APP_PORT}}/login")

@when(parsers.parse('the user executes steps for "{{tc_id}}"'))
def execute_test_scenario(page: Page, tc_id: str):
    # Action locators dynamically dispatched
    if "TC001" in tc_id:
        page.locator("[data-testid='input-email']").fill("qa.engineer@enterprise.io")
        page.locator("[data-testid='input-password']").fill("ValidPassword2026!")
        page.locator("[data-testid='button-login']").click()
    elif "TC006" in tc_id:
        for _ in range(5):
            page.locator("[data-testid='input-email']").fill("customer@enterprise.io")
            page.locator("[data-testid='input-password']").fill("WrongPass")
            page.locator("[data-testid='button-login']").click()

@then(parsers.parse('the system should satisfy expected result "{{expected_text}}"'))
def verify_outcome(page: Page, expected_text: str):
    expect(page.locator("body")).to_be_visible()
'''

    return {
        "feature_file": feature_content,
        "step_defs": step_defs_content
    }

